CREATE TABLE IF NOT EXISTS Cinemas(
	Cinema_ID   INTEGER[5] PRIMARY KEY,
	City_ID		INTEGER[5] NOT NULL,
	Cinema_Name VARCHAR[15] NOT NULL,
	FOREIGN KEY (City_ID) REFERENCES City(City_ID)

);
CREATE TABLE IF NOT EXISTS Screening(
	Movie_ID INTEGER[5] NOT NULL,
	Cinema_ID INTEGER[5] NOT NULL,
	Screen_ID	INTEGER[5] NOT NULL,
	Screen_Time	VARCHAR[20] NOT NULL,
	
	PRIMARY KEY(Cinema_ID, Movie_ID, Screen_ID, Screen_Time),
	FOREIGN KEY (Cinema_ID) REFERENCES Cinemas(Cinema_ID),
	FOREIGN KEY (Movie_ID) REFERENCES Movies(Movie_ID)
);

CREATE TABLE IF NOT EXISTS City(
	City_ID INTEGER[5] NOT NULL PRIMARY KEY,
	City_name VARCHAR[10] NOT NULL
);

CREATE TABLE IF NOT EXISTS Movies(
	Movie_ID INTEGER[5] PRIMARY KEY,
	Movie_title VARCHAR[15] NOT NULL,
	Movie_Duration INTEGER[5] NOT NULL
);


CREATE TABLE IF NOT EXISTS Booking(
	BT_ID INTEGER[5] PRIMARY KEY,
	Movie_ID INTEGER[5] NOT NULL,
	Cinema_ID INTEGER[5] NOT NULL,
	Screen_ID INTEGER[5] NOT NULL,
	SeatNum   INTEGER[5] NOT NULL CHECK(SeatNum BETWEEN 1 AND 10),
	
	
	UNIQUE(Movie_ID,Cinema_ID,Screen_ID,SeatNum),
	FOREIGN KEY (Movie_ID) REFERENCES Movies(Movie_ID),
	FOREIGN KEY (Cinema_ID) REFERENCES Cinemas(Cinema_ID),
	FOREIGN KEY (Screen_ID) REFERENCES Screening(Screen_ID)
);
